name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Authenticating kube 
      run: | 
        export KUBECONFIG="${{ secrets.config }}"
        kubectl get nodes 
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        context: <context name>  #If left unspecified, current-context from kubeconfig is used as default
      id: setcontext
    - name: list the nodes
      run: kubectl get nodes
    - name: Deploy in node APP
      run: kubectl --kubeconfig ./kubeconfig.yaml -n test set image deployment/nginx-deployment "nginx-deployment"=krishnaprasadkv/nodejs
    - name: Test the Testcases 
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
    - name: Build the Docker Image 
      run: docker build . --file Dockerfile --tag krishnaprasadkv/nodejs
    - name: Push the Docker Image 
      run: docker push krishnaprasadkv/nodejs
      
      env:
        CI: true
